function [scenario, egoVehicle] = myRoadrunnerStraightWaypoints()
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Generated by MATLAB(R) 23.2 (R2023b) and Automated Driving Toolbox 23.2 (R2023b).
% Generated on: 01-Feb-2024 21:44:49

% Construct a drivingScenario object.
scenario = drivingScenario;

% Add all road segments
roadCenters = [-201.94999747543 448.10133394875 0;
    -201.9686275044 472.11031129078 0;
    -201.96934588163 472.81995767736 0;
    -201.97704388319 474.9526016138 0;
    -201.98144854378 475.66223469437 0;
    -202.13002475747 498.72123648963 0;
    -202.1564954669 502.82948585878 0;
    -149.21364886572 639.82257076809 0;
    -146.93685477222 642.29608839816 0;
    -9.0399228821391 705.44690374577 0;
    -8.2938298906539 705.47087245815 0;
    -6.8521771624367 705.51718646993 0;
    134.84991021224 653.07160601557 0;
    137.50690371034 650.64031140229 0;
    198.409999217 511.69615449533 0;
    197.53113437008 261.69769930695 0;
    196.65226952317 11.699244118557 0;
    196.57320112533 -10.792242919912 0;
    196.57138294577 -11.337612729532 0;
    196.56919034696 -12.976587282532 0;
    196.56954934536 -13.521960004753 0;
    196.77952288825 -263.52187182696 0;
    196.98949643114 -513.52178364917 0;
    197.19946997403 -763.52169547137 0;
    197.40944351692 -1013.5216072936 0;
    197.44721634209 -1058.4949064591 0;
    197.4477734546 -1059.0402790059 0;
    197.45271917956 -1060.6792475362 0;
    197.45545346199 -1061.2246135132 0;
    198.75426139358 -1311.2212396863 0;
    200.05306932517 -1561.2178658595 0;
    200.17002177804 -1583.7290608777 0;
    200.17002420928 -1583.7295288468 0;
    200.17459408319 -1584.8692268529 0;
    200.14375195969 -1588.2694218044 0;
    200.11850883797 -1589.408849386 0;
    200.09243923882 -1590.5579732594 0;
    200.03881565764 -1594.0160747127 0;
    200.02924315837 -1595.1654544009 0;
    200.02922619282 -1595.1676649455 0;
    259.712962068 -1742.4438519906 0;
    406.05521046454 -1804.3810592639 0;
    406.37929259109 -1804.3835465395 0;
    553.25780029041 -1745.0903752319 0;
    553.81990485183 -1744.5397976543 0;
    615.26916481763 -1598.3417074933 0;
    615.26986352296 -1576.2437381173 0;
    615.26941913882 -1575.040166304 0;
    615.25215063381 -1571.4231917261 0;
    615.24110284496 -1570.2196705365 0;
    615.02988797586 -1548.1731785286 0];
headings = [90.0444592788391;90.0444592788391;90.085048013194;90.3285804193172;90.3691691536711;90.3691691536711;90.3691691536711;47.3714215172733;47.3714215172733;1.84003056541792;1.84003056541792;1.84003056541644;-42.4602219306966;-42.4602219306967;-90.2014214008409;-90.2014214008409;-90.2014214008409;-90.2014214008409;-90.1702284261201;-89.9830705777955;-89.9518776030743;-89.9518776030743;-89.9518776030743;-89.9518776030743;-89.9518776030743;-89.9518776030743;-89.9206846288715;-89.7335267836545;-89.7023338094534;-89.7023338094534;-89.7023338094534;-89.7023338094534;-89.7023338093085;-89.9066748959087;-91.1327214155098;-91.3370625021103;-91.2248955267648;-90.5518936746917;-90.4397266993458;-90.4397266993458;-45.4397266990943;-0.439867884870216;-0.439726699156918;44.4064577131979;44.4064577131978;89.9980440846859;89.9981883933099;90.0670275192097;90.4800622746089;90.5489014005079;90.5489014005079];
marking1 = [laneMarking('Unmarked')
    laneMarking('Unmarked')
    laneMarking('Unmarked')
    laneMarking('Unmarked')
    laneMarking('DoubleSolid', 'Color', [0.98 0.86 0.36], 'Width', 0.125)
    laneMarking('Solid', 'Width', 0.125)
    laneMarking('Unmarked')
    laneMarking('Unmarked')
    laneMarking('Unmarked')
    laneMarking('Unmarked')];
lanetypes1 = [laneType('Border')
    laneType('Shoulder')
    laneType('Shoulder')
    laneType('Driving')
    laneType('Driving')
    laneType('Driving')
    laneType('Shoulder')
    laneType('Shoulder')
    laneType('Border')];

marking2 = [laneMarking('Unmarked')
    laneMarking('Unmarked')
    laneMarking('Unmarked')
    laneMarking('Unmarked')
    laneMarking('DoubleSolid', 'Color', [0.98 0.86 0.36], 'Width', 0.125)
    laneMarking('Solid', 'Width', 0.125)
    laneMarking('Unmarked')
    laneMarking('Unmarked')
    laneMarking('Unmarked')
    laneMarking('Unmarked')];
lanetypes2 = [laneType('Border')
    laneType('Shoulder')
    laneType('Shoulder')
    laneType('Driving')
    laneType('Driving')
    laneType('Driving')
    laneType('Shoulder')
    laneType('Shoulder')
    laneType('Border')];

marking3 = [laneMarking('Unmarked')
    laneMarking('Unmarked')
    laneMarking('Unmarked')
    laneMarking('Unmarked')
    laneMarking('DoubleSolid', 'Color', [0.98 0.86 0.36], 'Width', 0.125)
    laneMarking('Solid', 'Width', 0.125)
    laneMarking('Unmarked')
    laneMarking('Unmarked')
    laneMarking('Unmarked')
    laneMarking('Unmarked')];
lanetypes3 = [laneType('Border')
    laneType('Shoulder')
    laneType('Shoulder')
    laneType('Driving')
    laneType('Driving')
    laneType('Driving')
    laneType('Shoulder')
    laneType('Shoulder')
    laneType('Border')];

marking4 = [laneMarking('Unmarked')
    laneMarking('Unmarked')
    laneMarking('Unmarked')
    laneMarking('Unmarked')
    laneMarking('DoubleSolid', 'Color', [0.98 0.86 0.36], 'Width', 0.125)
    laneMarking('Solid', 'Width', 0.125)
    laneMarking('Unmarked')
    laneMarking('Unmarked')
    laneMarking('Unmarked')
    laneMarking('Unmarked')];
lanetypes4 = [laneType('Border')
    laneType('Shoulder')
    laneType('Shoulder')
    laneType('Driving')
    laneType('Driving')
    laneType('Driving')
    laneType('Shoulder')
    laneType('Shoulder')
    laneType('Border')];

marking5 = [laneMarking('Unmarked')
    laneMarking('Unmarked')
    laneMarking('Unmarked')
    laneMarking('Unmarked')
    laneMarking('DoubleSolid', 'Color', [0.98 0.86 0.36], 'Width', 0.125)
    laneMarking('Solid', 'Width', 0.125)
    laneMarking('Unmarked')
    laneMarking('Unmarked')
    laneMarking('Unmarked')
    laneMarking('Unmarked')];
lanetypes5 = [laneType('Border')
    laneType('Shoulder')
    laneType('Shoulder')
    laneType('Driving')
    laneType('Driving')
    laneType('Driving')
    laneType('Shoulder')
    laneType('Shoulder')
    laneType('Border')];

marking6 = [laneMarking('Unmarked')
    laneMarking('Unmarked')
    laneMarking('Unmarked')
    laneMarking('Unmarked')
    laneMarking('DoubleSolid', 'Color', [0.98 0.86 0.36], 'Width', 0.125)
    laneMarking('Solid', 'Width', 0.125)
    laneMarking('Unmarked')
    laneMarking('Unmarked')
    laneMarking('Unmarked')
    laneMarking('Unmarked')];
lanetypes6 = [laneType('Border')
    laneType('Shoulder')
    laneType('Shoulder')
    laneType('Driving')
    laneType('Driving')
    laneType('Driving')
    laneType('Shoulder')
    laneType('Shoulder')
    laneType('Border')];

marking7 = [laneMarking('Unmarked')
    laneMarking('Unmarked')
    laneMarking('Unmarked')
    laneMarking('Unmarked')
    laneMarking('DoubleSolid', 'Color', [0.98 0.86 0.36], 'Width', 0.125)
    laneMarking('Solid', 'Width', 0.125)
    laneMarking('Unmarked')
    laneMarking('Unmarked')
    laneMarking('Unmarked')
    laneMarking('Unmarked')];
lanetypes7 = [laneType('Border')
    laneType('Shoulder')
    laneType('Shoulder')
    laneType('Driving')
    laneType('Driving')
    laneType('Driving')
    laneType('Shoulder')
    laneType('Shoulder')
    laneType('Border')];

marking8 = [laneMarking('Unmarked')
    laneMarking('Unmarked')
    laneMarking('Unmarked')
    laneMarking('Unmarked')
    laneMarking('DoubleSolid', 'Color', [0.98 0.86 0.36], 'Width', 0.125)
    laneMarking('Solid', 'Width', 0.125)
    laneMarking('Unmarked')
    laneMarking('Unmarked')
    laneMarking('Unmarked')
    laneMarking('Unmarked')];
lanetypes8 = [laneType('Border')
    laneType('Shoulder')
    laneType('Shoulder')
    laneType('Driving')
    laneType('Driving')
    laneType('Driving')
    laneType('Shoulder')
    laneType('Shoulder')
    laneType('Border')];

laneSpecifications = [lanespec([4 5], 'Width', [2 0.635 0.5 3.5 3.5 3.5 0.5 0.635 2], 'Marking', marking1, 'Type', lanetypes1)
    lanespec([4 5], 'Width', [2 0.635 0.5 3.5 3.5 3.5 0.5 0.635 2], 'Marking', marking2, 'Type', lanetypes2)
    lanespec([4 5], 'Width', [2 0.635 0.5 3.5 3.5 3.5 0.5 0.635 2], 'Marking', marking3, 'Type', lanetypes3)
    lanespec([4 5], 'Width', [2 0.635 0.5 3.5 3.5 3.5 0.5 0.635 2], 'Marking', marking4, 'Type', lanetypes4)
    lanespec([4 5], 'Width', [2 0.635 0.5 3.5 3.5 3.5 0.5 0.635 2], 'Marking', marking5, 'Type', lanetypes5)
    lanespec([4 5], 'Width', [2 0.635 0.5 3.5 3.5 3.5 0.5 0.635 2], 'Marking', marking6, 'Type', lanetypes6)
    lanespec([4 5], 'Width', [2 0.635 0.5 3.5 3.5 3.5 0.5 0.635 2], 'Marking', marking7, 'Type', lanetypes7)
    lanespec([4 5], 'Width', [2 0.635 0.5 3.5 3.5 3.5 0.5 0.635 2], 'Marking', marking8, 'Type', lanetypes8)];
lsConnector = laneSpecConnector('TaperShape', 'None');
compLaneSpecification = compositeLaneSpec(laneSpecifications, 'Connector', lsConnector, 'SegmentRange', [0.0145326249490531 0.0901703273019999 0.0901595715153335 0.601579066843807 0.00328427404313924 0.0926598273153265 0.0932112447942501 0.0144030632370902]);
road(scenario, roadCenters, 'Heading', headings, 'Lanes', compLaneSpecification, 'Name', 'Road');

% Add the ego vehicle
egoVehicle = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [198 400.32 0.01], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car');
waypoints = [198 400.32 0.01;
    198.05 390.54 0.01;
    197.97 380.57 0.01;
    197.9 372.61 0.01];
speed = 20;
trajectory(egoVehicle, waypoints, speed);

% Add the non-ego actors
car1 = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [197.903842654306 371.442885393323 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car1');
waypoints = [197.903842654306 371.442885393323 0;
    197.9 346.6 0;
    197.7 324.5 0;
    197.5 300.6 0;
    197.49 276.54 0.01;
    197.41 254.56 0.01;
    197.34 234.58 0.01;
    197.26 214.6 0.01;
    197.75 196.46 0.01;
    197.23 180.49 0.01;
    197.23 158.57 0.01;
    197.13 134.49 0.01;
    197.04 108.54 0.01;
    197.04 84.57 0.01;
    196.75 60.49 0.01;
    196.84 34.55 0.01;
    196.73 8.51 0.01;
    196.74 -17.34 0.01;
    196.64 -43.38 0.01;
    196.64 -65.4 0.01;
    196.53 -83.57 0.01;
    196.63 -101.55 0.01;
    196.7 -131.4 0;
    196.7 -159.48 0.01;
    196.7 -189.6 0.01;
    196.61 -219.43 0.01;
    196.7 -243.44 0.01;
    196.7 -271.43 0.01;
    196.79 -299.41 0.01;
    196.79 -327.4 0.01;
    196.8 -355.5 0;
    196.8 -383.5 0;
    196.7 -423.4 0;
    196.8 -459.4 0;
    196.8 -499.4 0;
    196.9 -539.5 0;
    196.9 -571.4 0;
    196.9 -609.3 0;
    197 -651.5 0;
    197.1 -695.4 0;
    197.2 -729.4 0;
    197.2 -765.4 0;
    197.17 -795.44 0.01;
    197.17 -829.39 0.01;
    197.17 -859.36 0.01;
    197.16 -879.4 0.01;
    197.16 -901.49 0.01;
    197.21 -921.49 0.01;
    197.21 -941.35 0.01;
    197.21 -973.45 0.01;
    197.37 -1009.36 0.01;
    197.3 -1047.4 0;
    197.4 -1079.4 0;
    197.5 -1107.4 0;
    197.7 -1137.4 0;
    197.9 -1167.4 0;
    198.1 -1199.4 0];
speed = [2;25;25;25;25;25;25;25;25;25;25;25;25;25;20;20;20;20;20;20;20;20;20;20;20;20;20;20;20;20;20;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;10;10;10;10;10;10;10;10;10;10;0.5];
yaw =  [-90;NaN;NaN;NaN;NaN;NaN;NaN;NaN;NaN;NaN;NaN;NaN;NaN;NaN;NaN;NaN;NaN;NaN;NaN;NaN;NaN;NaN;NaN;NaN;NaN;NaN;NaN;NaN;NaN;NaN;NaN;NaN;NaN;NaN;NaN;NaN;NaN;NaN;NaN;NaN;NaN;NaN;NaN;NaN;NaN;NaN;NaN;NaN;NaN;NaN;NaN;NaN;NaN;NaN;NaN;NaN;NaN];
trajectory(car1, waypoints, speed, 'Yaw', yaw);

