function [scenario, egoVehicle] = s_curve_road()
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Generated by MATLAB(R) 23.2 (R2023b) and Automated Driving Toolbox 23.2 (R2023b).
% Generated on: 08-Jan-2024 01:29:03

% Construct a drivingScenario object.
scenario = drivingScenario;

% Add all road segments
roadCenters = [5.21 -10.05 0;
    5.21 -4.95 0;
    5.21 -0.05 0;
    5.21 4.45 0;
    5.41 9.65 0;
    7.61 14.44 0;
    11.61 17.44 0;
    16 18.34 0;
    19.5 18.54 0;
    22.1 18.04 0;
    23.9 16.54 0;
    25.6 14.14 0;
    26.6 10.95 0;
    26.8 7.85 0;
    26.8 3.45 0;
    26.8 -0.75 0;
    26.9 -3.15 0;
    26.9 -6.35 0;
    27 -9.65 0;
    28.3 -11.94 0;
    31.5 -13.54 0;
    36.1 -13.64 0;
    38.99 -13.34 0;
    40.89 -11.84 0;
    42.59 -8.45 0;
    44.29 -3.45 0;
    44.69 1.95 0;
    44.39 5.65 0];
marking = [laneMarking('Solid', 'Color', [0.98 0.86 0.36])
    laneMarking('Dashed', 'Length', 2, 'Space', 3)
    laneMarking('Dashed', 'Length', 2, 'Space', 3)
    laneMarking('Dashed')];
laneSpecification = lanespec(3, 'Marking', marking);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road');

% Add the ego vehicle
egoVehicle = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [5.26 -7.47 0.01], ...
    'Mesh', driving.scenario.carMesh, ...
    'PlotColor', [0 114 189] / 255, ...
    'Name', 'Car');
waypoints = [5.26 -7.47 0.01;
    5.17 0.33 0.01;
    5.5 7.63 0.01;
    7.39 14.19 0.01;
    11.57 17.47 0.01;
    19.61 18.54 0.01;
    24.04 16.65 0.01;
    26.75 10.99 0.01;
    26.99 3.44 0.01;
    26.8 -6.5 0;
    28.6 -12.7 0;
    34.7 -14.1 0;
    40.46 -12.25 0.01;
    43.05 -7.56 0.01;
    44.58 -0.85 0.01;
    44.49 5.76 0];
speed = 30;
trajectory(egoVehicle, waypoints, speed);

% Add the non-ego actors
car1 = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [5.17 2.3 0.01], ...
    'Mesh', driving.scenario.carMesh, ...
    'PlotColor', [0.929 0.694 0.125], ...
    'Name', 'Car1');
waypoints = [5.17 2.3 0.01;
    6.06 11.23 0.01;
    10.56 17.27 0.01;
    18.23 18.8 0.01;
    25.41 15.44 0.01;
    27.04 9.31 0.01;
    26.85 0.97 0.01;
    26.85 -8.13 0.01;
    29.92 -13.98 0.01;
    35.38 -14.36 0.01;
    39.79 -13.21 0.01;
    43.24 -7.75 0.01;
    44.49 -1.81 0.01;
    44.49 5.76 0];
speed = [30;30;30;30;25;25;25;25;20;20;20;20;20;0.1];
trajectory(car1, waypoints, speed);

